# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-12 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lists',
        ),
    ]
