# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-12 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2017, 2, 12, 5, 9, 9, 381207, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.EmailField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
