# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170212_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='login.Item'),
        ),
    ]
